---
console_eventlog_verbosity: error
console_mouse: false
console_palette: dark
listen_port: 8888
# allow_hosts:
#   - entree.igetget.com
#   - entree.dev.didatrip.com
#   - entree-ws.igetget.com
#   - entree-ali.igetget.com
# view_filter: "~dst entree"