# -*- coding:utf-8 -*-
nginx:
	sudo ln -f  $(PWD)/autoproxy.pac /var/www/localhost/htdocs
	sudo ln -f  $(PWD)/iget.pac /var/www/localhost/htdocs

#	g++ -o nul  -Wall -Wextra  -pedantic -fsyntax-only -Wno-variadic-macros -std=c99 $(INCLUDES) -S ${CHK_SOURCES}
