# /usr/share/doc/alacritty-0.13.2/
# [shell]
# args = ["-l", "-c", "tmux attach || tmux"]
# program = "/bin/zsh"


[colors.bright]
black = "0x666666"
blue = "0x8cd0d3"
cyan = "0xb3ffff"
green = "0xbfebbf"
magenta = "0xfcace3"
red = "0xdca3a3"
white = "0xffffff"
yellow = "0xf0dfaf"

[colors.dim]
black = "0x000000"
blue = "0x82b0ec"
cyan = "0x9ac8e0"
green = "0x88ca9f"
magenta = "0xcaa6df"
red = "0xff9580"
white = "0x989898"
yellow = "0xd2b580"

[colors.normal]
black = "0x222222"
blue = "0x6ca0a3"
cyan = "0x93e0e3"
green = "0x7f9f7f"
magenta = "0xdc8cc3"
red = "0xcc9393"
white = "0x989898"
yellow = "0xd0bf8f"

[colors.primary]
background = "0x111111"
foreground = "0xdcdccc"

[font]
size = 15

[font.bold]
family = "Sarasa Term SC Nerd"
style = "Bold"

[font.bold_italic]
family = "Sarasa Term SC Nerd"
style = "Bold Italic"

[font.italic]
family = "Sarasa Term SC Nerd"
style = "Italic"

[font.normal]
family = "Sarasa Term SC Nerd"
style = "Regular"

[[hints.enabled]]
command = "open-with"
hyperlinks = true
post_processing = true
regex = "((ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+)|(([\\w\\.\\-_/]+/)*[\\w\\-_\\.]+\\.[\\w]+(:\\d+)?)"

[hints.enabled.binding]
key = "M"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Key2"
mode = "~Vi"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Y"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Super"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Super"

[[keyboard.bindings]]
action = "PasteSelection"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearHistory"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "A"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "V"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "V"
mode = "Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "Last"
key = "E"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "S"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "Key2"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "WordLeft"
key = "V"
mode = "Vi"

[[keyboard.bindings]]
action = "WordRight"
key = "E"
mode = "Vi"

[[keyboard.bindings]]
action = "First"
key = "A"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Q"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "G"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Control"

[selection]
save_to_clipboard = true

[window.padding]
x = 10
y = 10
