#!/bin/bash

options=$(echo -e "  Poweroff\n  Restart\n  Suspend\n  Logout\n  Stop xremap\n  Restart xremap")

selected_option=$(echo -e "$options" | rofi -dmenu -i -mesg "Bye "$USER"!" -config ~/.config/rofi/power.rasi)

# Handle the selected option
case $selected_option in
    "  Poweroff")
        systemctl poweroff
        ;;
    "  Restart")
        systemctl reboot
        ;;
    "  Suspend")
        systemctl suspend
        ;;
    "  Logout")
        pkill -KILL -u "$USER"
        ;;
    "  Stop xremap")
        systemctl --user stop xremap;pkill -9 xremap
        ;;
    "  Restart xremap")
        pkill xremap;pkill -9 xremap;systemctl --user restart xremap
        ;;
esac
