# -*- coding: utf-8 -*-
"""
Generate unified-scale dictionaries for egret_wubi_py (wubi+pinyin mixed schema).

v3 (2026-09-23) -- NO librime patch required, works on stock Squirrel/ibus:

  Problem: every wubi char entry uses comma-tokens ("kl,b0") from which the
  speller algebra derives 2/3/full codes.  Many chars share a 2-key prefix,
  so one input spelling ("kl") expands to several syllables; librime yields
  the first chunk unsorted, so the top candidate depends on arbitrary prism
  traversal order (kl->嗯, wq->傑, bn->䧩, gi->? ...).

  Fix, entirely at dictionary level:
    1. 2-key short-code OWNERSHIP follows the TRADITIONAL level-2 table
       (dicts/wubi86/wubi86.dict.yaml, 619 entries: kl=另, wq=你, gi=不,
       bn=也, bs=阿 ...).  Only the owner keeps a comma-token (derived
       2/3/full codes); every other char sharing that prefix is rewritten
       as a PLAIN full-code token (still typeable as full code, still found
       via completion).  Result: one input spelling expands to exactly one
       syllable -> deterministic first candidate on every runtime.
    2. 2-key prefixes that are valid PINYIN syllables (de, ren, shi, ...)
       get NO wubi owner: pinyin takes over completely, which is the whole
       point of the mixed schema (de->的, ren->人).
    3. Level-1 short codes (25, from the same traditional table) are emitted
       as plain "<letter>" tokens.
    4. Char weights are REGENERATED from the 25e9-char corpus table (知频,
       wb86_cn_dicts/8105): log-normalized to 1..1000, scaled by
       WUBI_CHAR_SCALE so pinyin readings win code collisions.  (Wanxiang
       char weights are chat-corpus-inflated: 嗯 898 > 另 747.)
    5. Word weights stay on wanxiang scale (base.small > 450, drops
       corpus-fragment glue words like 今天有).

Run:  python3 scripts/gen_wubi_py_unified_dicts.py
"""
import math
import os
import re
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
DICTS = os.path.join(os.path.dirname(HERE), "dicts")
OUT_DIR = os.path.join(DICTS, "egret_wubi_py")  # 本次方案生成的数据文件统一放这里
SRC_DIR = os.path.join(DICTS, "wb86_wangxiang_cn_dicts")
ZHIPIN_8105 = os.path.join(DICTS, "wb86_cn_dicts", "8105.dict.yaml")
WUBI86 = os.path.join(DICTS, "wubi86", "wubi86.dict.yaml")
PINYIN_8105 = os.path.join(DICTS, "wangxiang_cn_dicts", "8105.dict.yaml")

WUBI_CHAR_SCALE = 0.35
WEIGHT_KNEE = 600          # chars at/above this norm keep full weight
BASE_SMALL_THRESHOLD = 450


def entries_of(path):
    lines = open(path, encoding="utf-8").read().split("\n")
    i = lines.index("...")
    for l in lines[i + 1:]:
        if not l or l.startswith("#"):
            continue
        parts = l.split("\t")
        if len(parts) < 3:
            continue
        try:
            w = int(parts[2])
        except ValueError:
            continue
        yield parts


def header(name, comment_lines):
    return ("# generated by scripts/gen_wubi_py_unified_dicts.py -- DO NOT EDIT\n"
            + "".join(f"# {c}\n" for c in comment_lines)
            + "---\nname: %s\nversion: \"2025-09-23\"\nsort: by_weight\n...\n" % name)


def full_code(token):
    """'kl,b0' -> 'klb' ; 'e0,00' -> 'e' ; 'tr,xy' -> 'trxy'"""
    no_comma = token.replace(",", "")
    return no_comma.rstrip("0") or no_comma[0]


def strip_tone(s):
    """'dì' -> 'di', 'lǜ' -> 'lv'"""
    s = s.replace("ü", "v")
    return "".join(c for c in unicodedata.normalize("NFD", s)
                   if not unicodedata.combining(c))


def load_traditional_jianma():
    """Parse the classic wubi86 dict: level-1/2/3 short-code tables."""
    level1, level2, level3 = {}, {}, {}
    for parts in entries_of(WUBI86):
        if len(parts) < 2:
            continue
        ch, code = parts[0], parts[1]
        if len(ch) != 1:
            continue
        if len(code) == 1:
            level1[ch] = code
        elif len(code) == 2:
            level2.setdefault(code, ch)
        elif len(code) == 3:
            level3.setdefault(code, ch)
    return level1, level2, level3


def load_pinyin_syllables():
    """Tone-less pinyin syllable set from the wanxiang 8105 char table."""
    out = set()
    for parts in entries_of(PINYIN_8105):
        if len(parts) < 2:
            continue
        code = parts[1]
        if re.fullmatch(r"[a-züāáǎàōóǒòēéěèīíǐìūúǔùǖǘǚǜ]+", code):
            out.add(strip_tone(code))
    return out


def load_zhipin_char_weight():
    w = {}
    for parts in entries_of(ZHIPIN_8105):
        if len(parts) < 3:
            continue
        ch, weight = parts[0], parts[2]
        if len(ch) == 1 and weight.isdigit() and int(weight) > w.get(ch, 0):
            w[ch] = int(weight)
    return w


def gen_base_small():
    out = header("base.small", [
        "wb86 wubi-coded words on wanxiang weights, filtered weight > %d" % BASE_SMALL_THRESHOLD,
        "(same threshold as wangxiang base.small, drops corpus-fragment glue words)",
    ])
    n = 0
    for parts in entries_of(os.path.join(SRC_DIR, "base.dict.yaml")):
        ch, code, w = parts[0], parts[1], parts[2]
        if w.isdigit() and int(w) > BASE_SMALL_THRESHOLD:
            out += f"{ch}\t{code}\t{w}\n"
            n += 1
    with open(os.path.join(SRC_DIR, "base.small.dict.yaml"), "w", encoding="utf-8") as f:
        f.write(out)
    print("base.small.dict.yaml:", n, "entries")


def gen_chars():
    zhipin = load_zhipin_char_weight()
    w_max = max(zhipin.values())
    level1, level2, level3 = load_traditional_jianma()
    pinyin2 = {s for s in load_pinyin_syllables() if len(s) == 2}

    # 2字词的 2+2 派生码集合：降级字的 4 码全码若与之冲突则不发全码 token，
    # 让位给常用词（khlg=中国/䟧, xciy=经济/㢱）；降级字仍可用三级码或反查打出
    word_codes = set()
    for parts in entries_of(os.path.join(SRC_DIR, "base.small.dict.yaml")):
        if len(parts) < 2 or len(parts[0]) != 2:
            continue
        toks = parts[1].split(" ")
        if len(toks) == 2 and "," in toks[0] and "," in toks[1]:
            word_codes.add(toks[0].replace(",", "")[:2] + toks[1].replace(",", "")[:2])

    # weight for every char: corpus table, log-normalized, scaled
    weight = {}
    for ch, codes, w in [(p[0], p[1], p[2]) for p in entries_of(
            os.path.join(SRC_DIR, "chars.dict.yaml")) if len(p[0]) == 1 and p[2].isdigit()]:
        if ch in zhipin:
            full_n = max(1, int(round(
                1000.0 * math.log(1 + zhipin[ch]) / math.log(1 + w_max))))
            # 权重膝点: 超高频字(norm>=WEIGHT_KNEE, 简码主角)恢复真实权重,
            # 其余字压缩 0.35 让位拼音读法
            weight[ch] = full_n if full_n >= WEIGHT_KNEE else max(
                1, int(round(full_n * WUBI_CHAR_SCALE)))
        else:
            weight[ch] = 1  # beyond the 8105 corpus table: never win short codes

    # --- decide who keeps the comma-token per 2-key prefix ---
    # priority: traditional level-2 table > corpus weight.  Prefixes that are
    # pinyin syllables get no owner (pinyin takes over).
    rows = []   # (char, [codes], weight)
    for parts in entries_of(os.path.join(SRC_DIR, "chars.dict.yaml")):
        ch, codes = parts[0], parts[1]
        if len(ch) != 1:
            continue
        rows.append((ch, codes, weight.get(ch, 1)))

    owner = {}
    for ch, codes, w in sorted(rows, key=lambda r: -r[2]):
        f1 = full_code(codes.split(";")[0])
        p2 = f1[:2]
        if p2 in pinyin2 or p2 in owner:
            continue
        if p2 in level2:
            if level2[p2] == ch:
                owner[p2] = ch
        else:
            owner.setdefault(p2, ch)   # fallback: corpus weight (rows are weight-sorted)
    # traditional table may assign a code to a char we haven't reached (e.g.
    # its weight sort order differs); enforce it regardless
    for p2, ch in level2.items():
        if p2 not in pinyin2:
            owner[p2] = ch

    # 3-key spellings derived by comma-token owners: a demoted char must not
    # reuse one, else a single spelling would map to two syllables again
    reserved3 = {full_code(c.split(";")[0])[:3]
                 for c, ch2 in ((codes, ch) for ch, codes, w in rows)
                 if owner.get(full_code(c.split(";")[0])[:2]) == ch2}

    out = header("chars_wubi_py_x035", [
        "wubi chars, weights REGENERATED from the 25e9-char corpus table (知频):",
        "  log-normalized to 1..1000 then scaled by %.2f" % WUBI_CHAR_SCALE,
        "chars beyond the 8105 table get weight 1.",
        "2-key ownership follows the TRADITIONAL level-2 table (wubi86.dict.yaml):",
        "  only the owner keeps a comma token (derived 2/3 codes); all other chars",
        "  are plain tokens at their traditional level-3 code (or full code) ->",
        "  deterministic top candidate, no librime patch needed.  2-key prefixes",
        "  that are pinyin syllables (yi/de/ren/...) get no wubi owner: pinyin",
        "  takes over; those chars stay reachable via level-3 completion (就=yiy).",
    ])
    n = 0
    emitted = set()
    for ch, codes, w in rows:
        alts = codes.split(";")
        primary = alts[0]
        f1 = full_code(primary)
        p2 = f1[:2]
        lines = []
        if owner.get(p2) == ch:
            lines.append(f"{ch}\t{primary}\t{w}")           # keep comma token
            # 无逗号全码拼写：使 "ftjb"->都（全码精确）可达，否则只剩 2码歧义路径
            if len(f1) == 4 and f1 not in word_codes:
                lines.append(f"{ch}\t{f1}\t{w}")
        else:
            # demoted: traditional level-3 code (or first 3 of full) + full code
            p3 = level3.get(ch) or (f1[:3] if len(f1) > 3 else f1)
            if p3 in reserved3:
                p3 = f1
            lines.append(f"{ch}\t{p3}\t{w}")
            # 4码全码与 2字词简拼冲突时不发全码 token（词优先；字用三级码或反查）
            if f1 != p3 and f1 not in word_codes:
                lines.append(f"{ch}\t{f1}\t{w}")
        for a in alts[1:]:
            fa = full_code(a)
            if re.fullmatch(r"[a-y]", fa):
                continue  # first-level short codes live in the root wrapper (wubi_py_wubi.dict.yaml)
            lines.append(f"{ch}\t{fa}\t{w}")
        for l in lines:
            key = (ch, l.split("\t")[1])
            if key in emitted:
                continue
            emitted.add(key)
            out += l + "\n"
            n += 1
    # first-level short codes are served by the root wrapper (egret_wubi_py_wubi.dict.yaml);
    # plain letter tokens here would collide with pinyin syllables (e.g. e: 有 vs 额)
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "egret_wubi_py_chars.dict.yaml"), "w", encoding="utf-8") as f:
        f.write(out)
    print("egret_wubi_py_chars.dict.yaml:", n, "entries;", len(owner), "2-key owners;",
          len(pinyin2 & set(owner.keys())), "pinyin-colliding owners (should be 0)")



def gen_pinyin_toneless(src_rel, out_name):
    """Tone-less copy of a wanxiang pinyin dict: toned syllable tokens become
    plain tone-less tokens so same-sound entries share ONE syllable and get
    deterministic build-time weight ordering (no more derived-spelling
    cross-syllable races: e/é/è, le/乐/了 ...)."""
    out = header(out_name, [
        "tone-less copy of " + src_rel + " (tokens rewritten: \u00e9->e ...)",
        "same-sound chars/words merge into one syllable -> deterministic order",
    ])
    n = 0
    for parts in entries_of(os.path.join(DICTS, src_rel)):
        ch, code = parts[0], parts[1]
        w = parts[2] if len(parts) > 2 and parts[2].isdigit() else "1"
        toks = code.split(" ")
        if all(re.fullmatch(r"[a-z\u00fc\u0101-\u01d6\u00e0-\u00ff]+", t) for t in toks):
            code = " ".join(strip_tone(t) for t in toks)
        out += f"{ch}\t{code}\t{w}\n"
        n += 1
    with open(os.path.join(OUT_DIR, out_name + ".dict.yaml"), "w", encoding="utf-8") as f:
        f.write(out)
    print(out_name + ".dict.yaml:", n, "entries")



def gen_wubi_traditional():
    """Traditional-structure wubi dictionary for table_translator@wubi:
    - chars: explicit level-1/2/3 short codes + full codes (codes are the
      traditional ones from dicts/wubi86/wubi86.dict.yaml, i.e. the user's
      muscle memory; weights = corpus table log-normalized 0..1000)
    - words: every 2~5-char word from wb86_wangxiang base.small gets an
      explicit code generated by the classic 86 word-formation rules
      (2 chars: 2+2; 3 chars: 2+1+1; 4 chars: 1+1+1+1; 5+ chars: 1st=2, last two=1)
      weight = wanxiang word weight (LM-friendly)
    No derived short codes anywhere -> one spelling, one syllable -> the
    first candidate is deterministic on stock librime."""
    # char -> full codes: primary from chars.dict.yaml tokens (complete codes
    # with padding), plus wubi86.dict.yaml 3/4-col lines (len>=3 only: the 4th
    # column of level-1/2 lines is a TRUNCATED full code, e.g. 我=tr)
    fulls = {}   # char -> set of full codes
    level1, level2, level3 = load_traditional_jianma()
    for parts in entries_of(os.path.join(SRC_DIR, "chars.dict.yaml")):
        if len(parts) < 2:
            continue
        ch, codes = parts[0], parts[1]
        if len(ch) != 1:
            continue
        for tok in codes.split(";"):
            f = full_code(tok)
            if len(f) >= 3:
                fulls.setdefault(ch, set()).add(f)
    for parts in entries_of(WUBI86):
        if len(parts) < 3:
            continue
        ch, code = parts[0], parts[1]
        if len(ch) != 1:
            continue
        if len(parts) >= 4 and len(parts[3]) >= 3:
            fulls.setdefault(ch, set()).add(parts[3])
        elif len(code) >= 3:
            fulls.setdefault(ch, set()).add(code)
    zhipin = load_zhipin_char_weight()
    w_max = max(zhipin.values())

    def w_of(ch):
        if ch not in zhipin:
            return 1
        return max(1, int(round(1000.0 * math.log(1 + zhipin[ch]) / math.log(1 + w_max))))

    # UnityTableEncoder(造词) 从词库文件头的 encoder/rules 读取规则
    # —— 必须在 ... 之前的设置区里, 否则造词不工作
    enc_block = """encoder:
  rules:
    - length_equal: 2
      formula: "AaAbBaBb"
    - length_equal: 3
      formula: "AaAbBaCa"
    - length_equal: 4
      formula: "AaBaCaDa"
    - length_in_range: [5, 10]
      formula: "AaAbYaZa"
"""
    out = header("wubi_py_wubi", [
        "TRADITIONAL-structure wubi dictionary (for table_translator@wubi):",
        "  explicit level-1/2/3 short codes + full codes, classic 86 word codes.",
        "  No derived short codes -> deterministic candidates on stock librime.",
        "  char weights: corpus table (知频) log-normalized 0..1000",
        "  word weights: wanxiang word weights",
    ])
    out = out.replace("...\n", "") + enc_block + "...\n"
    n = 0
    # chars
    emitted = set()
    for ch, code in sorted(level1.items()):
        out += f"{ch}\t{code}\t{w_of(ch)}\n"; n += 1; emitted.add((ch, code))
    for code, ch in sorted(level2.items()):
        out += f"{ch}\t{code}\t{w_of(ch)}\n"; n += 1; emitted.add((ch, code))
    for code, ch in sorted(level3.items()):
        if (ch, code) not in emitted:
            out += f"{ch}\t{code}\t{w_of(ch)}\n"; n += 1; emitted.add((ch, code))
    for ch, fs in sorted(fulls.items()):
        for f in sorted(fs):
            if (ch, f) not in emitted:
                out += f"{ch}\t{f}\t{w_of(ch)}\n"; n += 1; emitted.add((ch, f))
    nchars = n
    # words: char -> first-2 / first-1 helpers need a canonical full code
    canon = {}   # char -> shortest full code (for word-formation)
    for ch, fs in fulls.items():
        canon[ch] = min(fs, key=lambda f: (len(f), f))
    nw = 0
    for parts in entries_of(os.path.join(SRC_DIR, "base.small.dict.yaml")):
        word, codes, w = parts[0], parts[1], parts[2]
        if len(word) < 2 or not w.isdigit():
            continue
        toks = codes.split(" ")
        if len(toks) != len(word):
            continue
        fs = [canon.get(c) for c in word]
        if any(f is None for f in fs):
            continue
        L = len(word)
        if L == 2:
            code = fs[0][:2] + fs[1][:2]
        elif L == 3:
            code = fs[0][:2] + fs[1][:1] + fs[2][:1]
        elif L == 4:
            code = "".join(f[:1] for f in fs)
        else:
            code = fs[0][:2] + fs[-2][:1] + fs[-1][:1]
        out += f"{word}\t{code}\t{w}\n"
        nw += 1
    n += nw
    # 薄包装(根) + 数据文件(dicts/): chars 与 words 分文件, 便于维护
    # 包装头: encoder 造词规则 + import_tables 引用两个数据文件
    wrapper = header("egret_wubi_py_wubi", [
        "TRADITIONAL-structure wubi dictionary (for table_translator@egret_wubi_py_wubi):",
        "  thin wrapper: data in dicts/egret_wubi_py_wubi_{chars,words}.dict.yaml",
        "  char weights: corpus table (知频) log-normalized 0..1000",
        "  word weights: wanxiang word weights",
    ]).replace("...\n", "")
    wrapper += """encoder:
  rules:
    - length_equal: 2
      formula: "AaAbBaBb"
    - length_equal: 3
      formula: "AaAbBaCa"
    - length_equal: 4
      formula: "AaBaCaDa"
    - length_in_range: [5, 10]
      formula: "AaAbYaZa"
import_tables:
  - dicts/egret_wubi_py/egret_wubi_py_wubi_chars
  - dicts/egret_wubi_py/egret_wubi_py_wubi_words
  - dicts/egret_wubi_py/egret_wubi_py_user_phrases
...
"""
    # 单字与词组分别写入数据文件
    char_entries, word_entries = [], []
    for line in out.split("\n"):
        if not line or "\t" not in line:
            continue
        (word_entries if len(line.split("\t")[0]) >= 2 else char_entries).append(line)
    with open(os.path.join(OUT_DIR, "egret_wubi_py_wubi_chars.dict.yaml"), "w", encoding="utf-8") as f:
        f.write(header("egret_wubi_py_wubi_chars", [
            "traditional wubi chars (level-1/2/3 short codes + full codes)",
            "(imported by ../../egret_wubi_py_wubi.dict.yaml)",
        ]) + "\n".join(char_entries) + "\n")
    with open(os.path.join(OUT_DIR, "egret_wubi_py_wubi_words.dict.yaml"), "w", encoding="utf-8") as f:
        f.write(header("egret_wubi_py_wubi_words", [
            "traditional wubi words (classic 86 word-formation codes)",
            "(imported by ../../egret_wubi_py_wubi.dict.yaml)",
        ]) + "\n".join(word_entries) + "\n")
    with open(os.path.join(os.path.dirname(DICTS), "egret_wubi_py_wubi.dict.yaml"), "w", encoding="utf-8") as f:
        f.write(wrapper)
        print("egret_wubi_py_wubi:", nchars, "char entries +", nw, "words (root wrapper + dicts/)")



if __name__ == "__main__":
    gen_base_small()
    gen_chars()
    gen_pinyin_toneless("wangxiang_cn_dicts/8105.dict.yaml", "egret_wubi_py_pinyin_8105")
    gen_pinyin_toneless("wangxiang_cn_dicts/base.small.dict.yaml", "egret_wubi_py_pinyin_base_small")
    gen_wubi_traditional()
