# -*- coding: utf-8 -*-
"""
为 egret_wubi_py（五笔+拼音混输方案）生成统一量级的词库数据文件。

v3 (2026-09-23) -- 不需要 librime patch，原版 Squirrel/ibus 即可工作：

  问题：五笔字表的每个条目都用逗号 token（如 "kl,b0"），speller 代数
  会从中派生出 2 码/3 码/全码。很多字共享同一个 2 键前缀，于是同一个输入
  拼写（如 "kl"）会展开成多个音节；librime 对第一个 chunk 不排序，首候选
  就取决于 prism 的任意遍历顺序（kl->嗯, wq->傑, bn->䧩, gi->? ...）。

  修复完全在词库层面完成：
    1. 2 键简码的 OWNERSHIP（归属）遵循传统 86 版二级简码表
       （dicts/wubi86/wubi86.dict.yaml，619 条：kl=另, wq=你, gi=不,
       bn=也, bs=阿 ...）。只有 owner 字保留逗号 token（派生 2/3/全码）；
       共享该前缀的其他字一律改写为纯全码 token（仍可打全码、仍可
       通过补全找到）。结果：一个输入拼写恰好展开成一个音节 →
       首候选在任何运行时都是确定的。
    2. 本身是合法拼音音节的 2 键前缀（de, ren, shi, ...）不设五笔
       owner：拼音完全接管——这正是混输方案的意义（de->的, ren->人）。
    3. 一级简码（25 个，来自同一传统表）以纯 "<字母>" token 输出。
    4. 字权重从 250 亿字语料表（知频, wb86_cn_dicts/8105）重新生成：
       log 归一化到 1..1000，再乘 WUBI_CHAR_SCALE 缩放，让拼音读法在
       码位冲突时胜出。（万象字权重被聊天语料抬高：嗯 898 > 另 747。）
    5. 词权重保持万象量级（base.small > 450，过滤掉今天有之类
       语料碎片胶水词）。

数据流总览：

  wubi86.dict.yaml ──┐
  知频 8105 ─────────┤
  chars.dict.yaml ───┼─→ gen_chars ─────→ egret_wubi_py_chars（混合库字表）
  base.small ────────┤
  万象8105(音节) ────┘

  base.dict.yaml ──→ gen_base_small → base.small ─┬─→ gen_chars（word_codes 冲突集）
                                                  └─→ gen_wubi_traditional
  万象 8105/base.small ─→ gen_pinyin_toneless ×2 → 拼音无调化字表/词表
  wubi86 + chars + base.small + 知频 ─→ gen_wubi_traditional
      → 传统库 chars/words + 根包装

注意：所有生成文件（OUT_DIR 及根包装）均带 DO NOT EDIT 头——手改会被
下次运行覆盖；用户自定义词组写在 egret_wubi_py_user_phrases.dict.yaml
（gen 只在根包装里引用，不覆盖）。

运行：  python3 scripts/gen_wubi_py_unified_dicts.py
"""
import math
import os
import re
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
DICTS = os.path.join(os.path.dirname(HERE), "dicts")
OUT_DIR = os.path.join(DICTS, "egret_wubi_py")  # 本次方案生成的数据文件统一放这里
SRC_DIR = os.path.join(DICTS, "wb86_wangxiang_cn_dicts")
ZHIPIN_8105 = os.path.join(DICTS, "wb86_cn_dicts", "8105.dict.yaml")
WUBI86 = os.path.join(DICTS, "wubi86", "wubi86.dict.yaml")
PINYIN_8105 = os.path.join(DICTS, "wangxiang_cn_dicts", "8105.dict.yaml")

WUBI_CHAR_SCALE = 0.35
WEIGHT_KNEE = 600          # 归一化权重达到/超过该膝点的字保留真实权重
BASE_SMALL_THRESHOLD = 450


def entries_of(path):
    """读取词库 yaml，逐条产出数据行。

    输入: 词库 yaml 文件路径（取 "..." 之后的正文）。
    输出: 迭代器，逐条产出 tab 分割的 (字词, 码, 权重, ...) 元组；
          自动跳过空行、# 注释行和权重非数字的行。
    """
    lines = open(path, encoding="utf-8").read().split("\n")
    i = lines.index("...")
    for l in lines[i + 1:]:
        if not l or l.startswith("#"):
            continue
        parts = l.split("\t")
        if len(parts) < 3:
            continue
        try:
            w = int(parts[2])
        except ValueError:
            continue
        yield parts


def header(name, comment_lines):
    """生成标准文件头。

    输入: 词库名 name + 注释行列表 comment_lines。
    输出: 头文本字符串（DO NOT EDIT 标记 + 注释 + name/version/sort 元数据），
          由各 gen_* 拼在生成文件开头。
    """
    return ("# generated by scripts/gen_wubi_py_unified_dicts.py -- DO NOT EDIT\n"
            + "".join(f"# {c}\n" for c in comment_lines)
            + "---\nname: %s\nversion: \"2025-09-23\"\nsort: by_weight\n...\n" % name)


def full_code(token):
    """去掉逗号与补位 0，还原全码。

    输入: 逗号 token（'kl,b0' / 'e0,00' / 'tr,xy'）。
    输出: 全码（'klb' / 'e' / 'trxy'）。
    """
    no_comma = token.replace(",", "")
    return no_comma.rstrip("0") or no_comma[0]


def strip_tone(s):
    """去声调（含 ü→v）。

    输入: 带调拼音字符串（'dì' / 'lǜ'）。
    输出: 无调字符串（'di' / 'lv'）。
    """
    s = s.replace("ü", "v")
    return "".join(c for c in unicodedata.normalize("NFD", s)
                   if not unicodedata.combining(c))


def load_traditional_jianma():
    """解析经典 86 版五笔字表的简码。

    输入: WUBI86（dicts/wubi86/wubi86.dict.yaml）。
    输出: (level1, level2, level3) 三个 dict——一/二/三级简码表
          （level1: {字→码}; level2/3: {码→字}）。
    """
    level1, level2, level3 = {}, {}, {}
    for parts in entries_of(WUBI86):
        if len(parts) < 2:
            continue
        ch, code = parts[0], parts[1]
        if len(ch) != 1:
            continue
        if len(code) == 1:
            level1[ch] = code
        elif len(code) == 2:
            level2.setdefault(code, ch)
        elif len(code) == 3:
            level3.setdefault(code, ch)
    return level1, level2, level3


def load_pinyin_syllables():
    """提取拼音音节集合。

    输入: PINYIN_8105（dicts/wangxiang_cn_dicts/8105.dict.yaml）。
    输出: 去调后的拼音音节集合 set（如 {de, ren, shi, ...}），
          gen_chars 用来判断 2 键前缀是否归拼音接管。
    """
    out = set()
    for parts in entries_of(PINYIN_8105):
        if len(parts) < 2:
            continue
        code = parts[1]
        if re.fullmatch(r"[a-züāáǎàōóǒòēéěèīíǐìūúǔùǖǘǚǜ]+", code):
            out.add(strip_tone(code))
    return out


def load_zhipin_char_weight():
    """读取知频字频。

    输入: ZHIPIN_8105（dicts/wb86_cn_dicts/8105.dict.yaml，250 亿字语料表）。
    输出: {字: 最高语料频次} dict（同字多行取最大值），
          供 gen_chars / gen_wubi_traditional 做 log 归一化权重。
    """
    w = {}
    for parts in entries_of(ZHIPIN_8105):
        if len(parts) < 3:
            continue
        ch, weight = parts[0], parts[2]
        if len(ch) == 1 and weight.isdigit() and int(weight) > w.get(ch, 0):
            w[ch] = int(weight)
    return w


def gen_base_small():
    """生成过滤后的五笔码词组表。

    输入: dicts/wb86_wangxiang_cn_dicts/base.dict.yaml（万象全量五笔码词组）。
    过滤: 只保留权重 > BASE_SMALL_THRESHOLD(450) 的条目，滤掉
          今天有之类语料碎片胶水词。
    输出: 写 dicts/wb86_wangxiang_cn_dicts/base.small.dict.yaml（base.small），
          供混合库与 gen_chars/gen_wubi_traditional 复用；
          stdout 打印条目数。
    """
    out = header("base.small", [
        "wb86 五笔码词组，万象权重，过滤权重 <= %d" % BASE_SMALL_THRESHOLD,
        "（与万象 base.small 同一阈值，滤掉语料碎片胶水词）",
    ])
    n = 0
    for parts in entries_of(os.path.join(SRC_DIR, "base.dict.yaml")):
        ch, code, w = parts[0], parts[1], parts[2]
        if w.isdigit() and int(w) > BASE_SMALL_THRESHOLD:
            out += f"{ch}\t{code}\t{w}\n"
            n += 1
    with open(os.path.join(SRC_DIR, "base.small.dict.yaml"), "w", encoding="utf-8") as f:
        f.write(out)
    print("base.small.dict.yaml:", n, "entries")


def gen_chars():
    """生成混合库字表（最核心）：2 键简码 ownership 裁决 + 知频权重重建。

    输入（5 个源）:
      - dicts/wb86_wangxiang_cn_dicts/chars.dict.yaml（五笔单字 + 逗号 token 码）
      - 上一步的 base.small.dict.yaml（提取 2 字词 2+2 派生码集合 word_codes，
        用于全码让位）
      - 知频 8105 表（字权重：log 归一化 0-1000，>=膝点 600 保留原值，
        否则 × WUBI_CHAR_SCALE(0.35)）
      - 传统 86 表（二级简码 owner 裁决 + 三级码，经 load_traditional_jianma）
      - 万象 8105 表（2 键拼音音节集合，拼音前缀不设五笔 owner，
        经 load_pinyin_syllables）
    输出:
      写 dicts/egret_wubi_py/egret_wubi_py_chars.dict.yaml
      （chars_wubi_py_x035）：
        - owner 字：保留逗号 token（+ 无逗号全码，若不与 2 字词冲突）
        - 被降级字：传统三级码（或全码前 3 位）+ 全码
        - 一级简码（[a-y]）不发，留给根包装
      stdout 打印：条目数、2 键 owner 数、与拼音冲突的 owner 数（应为 0）。
    """
    zhipin = load_zhipin_char_weight()
    w_max = max(zhipin.values())
    level1, level2, level3 = load_traditional_jianma()
    pinyin2 = {s for s in load_pinyin_syllables() if len(s) == 2}

    # 2字词的 2+2 派生码集合：降级字的 4 码全码若与之冲突则不发全码 token，
    # 让位给常用词（khlg=中国/䟧, xciy=经济/㢱）；降级字仍可用三级码或反查打出
    word_codes = set()
    for parts in entries_of(os.path.join(SRC_DIR, "base.small.dict.yaml")):
        if len(parts) < 2 or len(parts[0]) != 2:
            continue
        toks = parts[1].split(" ")
        if len(toks) == 2 and "," in toks[0] and "," in toks[1]:
            word_codes.add(toks[0].replace(",", "")[:2] + toks[1].replace(",", "")[:2])

    # 每个字的权重：来自语料表，log 归一化后按比例缩放
    weight = {}
    for ch, codes, w in [(p[0], p[1], p[2]) for p in entries_of(
            os.path.join(SRC_DIR, "chars.dict.yaml")) if len(p[0]) == 1 and p[2].isdigit()]:
        if ch in zhipin:
            full_n = max(1, int(round(
                1000.0 * math.log(1 + zhipin[ch]) / math.log(1 + w_max))))
            # 权重膝点: 超高频字(norm>=WEIGHT_KNEE, 简码主角)恢复真实权重,
            # 其余字压缩 0.35 让位拼音读法
            weight[ch] = full_n if full_n >= WEIGHT_KNEE else max(
                1, int(round(full_n * WUBI_CHAR_SCALE)))
        else:
            weight[ch] = 1  # 8105 语料表之外的字：永远赢不了简码

    # --- 决定每个 2 键前缀的逗号 token 归谁（ownership）---
    # 优先级：传统二级简码表 > 语料权重。是拼音音节的前缀不设 owner
    # （拼音接管）。
    rows = []   # (char, [codes], weight)
    for parts in entries_of(os.path.join(SRC_DIR, "chars.dict.yaml")):
        ch, codes = parts[0], parts[1]
        if len(ch) != 1:
            continue
        rows.append((ch, codes, weight.get(ch, 1)))

    owner = {}
    for ch, codes, w in sorted(rows, key=lambda r: -r[2]):
        f1 = full_code(codes.split(";")[0])
        p2 = f1[:2]
        if p2 in pinyin2 or p2 in owner:
            continue
        if p2 in level2:
            if level2[p2] == ch:
                owner[p2] = ch
        else:
            owner.setdefault(p2, ch)   # 兜底：按语料权重（rows 已按权重排序）
    # 传统表可能把某码分给了权重排序中尚未遍历到的字（权重排序与
    # 传统表不一致），这里无条件强制生效
    for p2, ch in level2.items():
        if p2 not in pinyin2:
            owner[p2] = ch

    # 保留字集：owner 字的逗号 token 会派生出 3 键拼写，被降级的字不得
    # 复用同一个 3 键拼写，否则一个拼写又会映射到两个音节
    reserved3 = {full_code(c.split(";")[0])[:3]
                 for c, ch2 in ((codes, ch) for ch, codes, w in rows)
                 if owner.get(full_code(c.split(";")[0])[:2]) == ch2}

    out = header("chars_wubi_py_x035", [
        "五笔字表，权重从 250 亿字语料表（知频）重新生成：",
        "  log 归一化到 1..1000，再乘 %.2f 缩放" % WUBI_CHAR_SCALE,
        "8105 表之外的字权重为 1。",
        "2 键归属遵循传统二级简码表（wubi86.dict.yaml）：",
        "  只有 owner 字保留逗号 token（派生 2/3 码）；其余字一律为",
        "  传统三级码（或全码）的纯 token → 首候选确定，无需 librime",
        "  patch。本身是拼音音节的 2 键前缀（yi/de/ren/...）不设五笔",
        "  owner：拼音接管；这些字仍可通过三级码补全打出（就=yiy）。",
    ])
    n = 0
    emitted = set()
    for ch, codes, w in rows:
        alts = codes.split(";")
        primary = alts[0]
        f1 = full_code(primary)
        p2 = f1[:2]
        lines = []
        if owner.get(p2) == ch:
            lines.append(f"{ch}\t{primary}\t{w}")           # 保留逗号 token
            # 无逗号全码拼写：使 "ftjb"->都（全码精确）可达，否则只剩 2码歧义路径
            if len(f1) == 4 and f1 not in word_codes:
                lines.append(f"{ch}\t{f1}\t{w}")
        else:
            # 被降级：取传统三级码（或全码前 3 位）+ 全码
            p3 = level3.get(ch) or (f1[:3] if len(f1) > 3 else f1)
            if p3 in reserved3:
                p3 = f1
            lines.append(f"{ch}\t{p3}\t{w}")
            # 4码全码与 2字词简拼冲突时不发全码 token（词优先；字用三级码或反查）
            if f1 != p3 and f1 not in word_codes:
                lines.append(f"{ch}\t{f1}\t{w}")
        for a in alts[1:]:
            fa = full_code(a)
            if re.fullmatch(r"[a-y]", fa):
                continue  # 一级简码由根包装（wubi_py_wubi.dict.yaml）负责，此处不发
            lines.append(f"{ch}\t{fa}\t{w}")
        for l in lines:
            key = (ch, l.split("\t")[1])
            if key in emitted:
                continue
            emitted.add(key)
            out += l + "\n"
            n += 1
    # 一级简码由根包装（egret_wubi_py_wubi.dict.yaml）负责；
    # 此处若发纯字母 token 会与拼音音节冲突（如 e：有 vs 额）
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "egret_wubi_py_chars.dict.yaml"), "w", encoding="utf-8") as f:
        f.write(out)
    print("egret_wubi_py_chars.dict.yaml:", n, "entries;", len(owner), "2-key owners;",
          len(pinyin2 & set(owner.keys())), "pinyin-colliding owners (should be 0)")



def gen_pinyin_toneless(src_rel, out_name):
    """生成万象拼音词库的无调化副本：带调音节 token 改写为无调 token，
    同音条目合并到同一个音节，构建期权重排序即为确定（消除派生拼写
    跨音节竞争：e/é/è、le/乐/了 ...）。

    输入: dicts/ 下指定的万象拼音词库（src_rel 相对 dicts/ 的路径）。
    变换: 所有带调音节 token 无调化（é→e），权重缺省补 1。
    输出: 写 dicts/egret_wubi_py/{out_name}.dict.yaml。主流程调用两次：
      - wangxiang_cn_dicts/8105.dict.yaml → egret_wubi_py_pinyin_8105
      - wangxiang_cn_dicts/base.small.dict.yaml → egret_wubi_py_pinyin_base_small
    """
    out = header(out_name, [
        src_rel + " 的无调化副本（token 改写：\u00e9->e ...）",
        "同音字/词合并到同一音节 → 顺序确定",
    ])
    n = 0
    for parts in entries_of(os.path.join(DICTS, src_rel)):
        ch, code = parts[0], parts[1]
        w = parts[2] if len(parts) > 2 and parts[2].isdigit() else "1"
        toks = code.split(" ")
        if all(re.fullmatch(r"[a-z\u00fc\u0101-\u01d6\u00e0-\u00ff]+", t) for t in toks):
            code = " ".join(strip_tone(t) for t in toks)
        out += f"{ch}\t{code}\t{w}\n"
        n += 1
    with open(os.path.join(OUT_DIR, out_name + ".dict.yaml"), "w", encoding="utf-8") as f:
        f.write(out)
    print(out_name + ".dict.yaml:", n, "entries")



def gen_wubi_traditional():
    """为 table_translator@wubi 生成传统结构五笔词库：
    - 字：显式的一/二/三级简码 + 全码（码就是传统 86 版
      dicts/wubi86/wubi86.dict.yaml 里的码，即用户肌肉记忆；
      权重 = 语料表 log 归一化 0..1000）
    - 词：wb86_wangxiang base.small 中所有 2~5 字词都显式生成词码，
      按经典 86 版造词规则（2 字: 2+2; 3 字: 2+1+1; 4 字: 1+1+1+1;
      5+ 字: 首字取 2, 末两字各取 1），权重 = 万象词权重（对 LM 友好）
    全程无派生简码 → 一个拼写一个音节 → 原版 librime 上首候选确定。

    输入（4 个源）:
      - dicts/wb86_wangxiang_cn_dicts/chars.dict.yaml（全码来源之一，
        含补位的完整码 token）
      - dicts/wubi86/wubi86.dict.yaml（一/二/三级简码 + 第 4 列全码，
        仅取长度 >=3 的：一/二级行第 4 列是被截断的全码，如 我=tr）
      - 知频 8105 表（字权重：log 归一化 0..1000，不缩放）
      - base.small.dict.yaml（词组源，每字需要一个规范全码 canon 取码）
    输出（3 个文件）:
      1. dicts/egret_wubi_py/egret_wubi_py_wubi_chars.dict.yaml
         （单字：显式一/二/三级简码 + 全码）
      2. dicts/egret_wubi_py/egret_wubi_py_wubi_words.dict.yaml
         （词组：显式词码 + 万象权重）
      3. 仓库根 egret_wubi_py_wubi.dict.yaml（薄包装：encoder/rules
         造词规则 + import_tables 引入上述两数据文件 + 用户词组表；
         部署时软链到 Rime 用户目录根）
    """
    # 字 -> 全码集合：来自 chars.dict.yaml 的 token（含补位的完整码），
    # 加上 wubi86.dict.yaml 的 3/4 列行（只取长度>=3 的：一/二级行的
    # 第 4 列是被截断的全码，如 我=tr）
    fulls = {}   # 字 -> 全码集合
    level1, level2, level3 = load_traditional_jianma()
    for parts in entries_of(os.path.join(SRC_DIR, "chars.dict.yaml")):
        if len(parts) < 2:
            continue
        ch, codes = parts[0], parts[1]
        if len(ch) != 1:
            continue
        for tok in codes.split(";"):
            f = full_code(tok)
            if len(f) >= 3:
                fulls.setdefault(ch, set()).add(f)
    for parts in entries_of(WUBI86):
        if len(parts) < 3:
            continue
        ch, code = parts[0], parts[1]
        if len(ch) != 1:
            continue
        if len(parts) >= 4 and len(parts[3]) >= 3:
            fulls.setdefault(ch, set()).add(parts[3])
        elif len(code) >= 3:
            fulls.setdefault(ch, set()).add(code)
    zhipin = load_zhipin_char_weight()
    w_max = max(zhipin.values())

    def w_of(ch):
        if ch not in zhipin:
            return 1
        return max(1, int(round(1000.0 * math.log(1 + zhipin[ch]) / math.log(1 + w_max))))

    # UnityTableEncoder(造词) 从词库文件头的 encoder/rules 读取规则
    # —— 必须在 ... 之前的设置区里, 否则造词不工作
    enc_block = """encoder:
  rules:
    - length_equal: 2
      formula: "AaAbBaBb"
    - length_equal: 3
      formula: "AaAbBaCa"
    - length_equal: 4
      formula: "AaBaCaDa"
    - length_in_range: [5, 10]
      formula: "AaAbYaZa"
"""
    out = header("wubi_py_wubi", [
        "传统结构五笔词库（供 table_translator@wubi）：",
        "  显式一/二/三级简码 + 全码，经典 86 版词码。",
        "  无派生简码 → 原版 librime 上候选确定。",
        "  字权重：语料表（知频）log 归一化 0..1000",
        "  词权重：万象词权重",
    ])
    out = out.replace("...\n", "") + enc_block + "...\n"
    n = 0
    # chars
    emitted = set()
    for ch, code in sorted(level1.items()):
        out += f"{ch}\t{code}\t{w_of(ch)}\n"; n += 1; emitted.add((ch, code))
    for code, ch in sorted(level2.items()):
        out += f"{ch}\t{code}\t{w_of(ch)}\n"; n += 1; emitted.add((ch, code))
    for code, ch in sorted(level3.items()):
        if (ch, code) not in emitted:
            out += f"{ch}\t{code}\t{w_of(ch)}\n"; n += 1; emitted.add((ch, code))
    for ch, fs in sorted(fulls.items()):
        for f in sorted(fs):
            if (ch, f) not in emitted:
                out += f"{ch}\t{f}\t{w_of(ch)}\n"; n += 1; emitted.add((ch, f))
    nchars = n
    # 词组：造词取码需要每字有一个规范全码（见 canon）
    canon = {}   # 字 -> 最短全码（供造词规则取码用）
    for ch, fs in fulls.items():
        canon[ch] = min(fs, key=lambda f: (len(f), f))
    nw = 0
    for parts in entries_of(os.path.join(SRC_DIR, "base.small.dict.yaml")):
        word, codes, w = parts[0], parts[1], parts[2]
        if len(word) < 2 or not w.isdigit():
            continue
        toks = codes.split(" ")
        if len(toks) != len(word):
            continue
        fs = [canon.get(c) for c in word]
        if any(f is None for f in fs):
            continue
        L = len(word)
        if L == 2:
            code = fs[0][:2] + fs[1][:2]
        elif L == 3:
            code = fs[0][:2] + fs[1][:1] + fs[2][:1]
        elif L == 4:
            code = "".join(f[:1] for f in fs)
        else:
            code = fs[0][:2] + fs[-2][:1] + fs[-1][:1]
        out += f"{word}\t{code}\t{w}\n"
        nw += 1
    n += nw
    # 薄包装(根) + 数据文件(dicts/): chars 与 words 分文件, 便于维护
    # 包装头: encoder 造词规则 + import_tables 引用两个数据文件
    wrapper = header("egret_wubi_py_wubi", [
        "传统结构五笔词库（供 table_translator@egret_wubi_py_wubi）：",
        "  薄包装：数据在 dicts/egret_wubi_py_wubi_{chars,words}.dict.yaml",
        "  字权重：语料表（知频）log 归一化 0..1000",
        "  词权重：万象词权重",
    ]).replace("...\n", "")
    wrapper += """encoder:
  rules:
    - length_equal: 2
      formula: "AaAbBaBb"
    - length_equal: 3
      formula: "AaAbBaCa"
    - length_equal: 4
      formula: "AaBaCaDa"
    - length_in_range: [5, 10]
      formula: "AaAbYaZa"
import_tables:
  - dicts/egret_wubi_py/egret_wubi_py_wubi_chars
  - dicts/egret_wubi_py/egret_wubi_py_wubi_words
  - dicts/egret_wubi_py/egret_wubi_py_user_phrases
...
"""
    # 单字与词组分别写入数据文件
    char_entries, word_entries = [], []
    for line in out.split("\n"):
        if not line or "\t" not in line:
            continue
        (word_entries if len(line.split("\t")[0]) >= 2 else char_entries).append(line)
    with open(os.path.join(OUT_DIR, "egret_wubi_py_wubi_chars.dict.yaml"), "w", encoding="utf-8") as f:
        f.write(header("egret_wubi_py_wubi_chars", [
            "传统五笔字表（一/二/三级简码 + 全码）",
            "（由 ../../egret_wubi_py_wubi.dict.yaml 引入）",
        ]) + "\n".join(char_entries) + "\n")
    with open(os.path.join(OUT_DIR, "egret_wubi_py_wubi_words.dict.yaml"), "w", encoding="utf-8") as f:
        f.write(header("egret_wubi_py_wubi_words", [
            "传统五笔词组（经典 86 版造词码）",
            "（由 ../../egret_wubi_py_wubi.dict.yaml 引入）",
        ]) + "\n".join(word_entries) + "\n")
    with open(os.path.join(os.path.dirname(DICTS), "egret_wubi_py_wubi.dict.yaml"), "w", encoding="utf-8") as f:
        f.write(wrapper)
        print("egret_wubi_py_wubi:", nchars, "char entries +", nw, "words (root wrapper + dicts/)")



if __name__ == "__main__":
    gen_base_small()
    gen_chars()
    gen_pinyin_toneless("wangxiang_cn_dicts/8105.dict.yaml", "egret_wubi_py_pinyin_8105")
    gen_pinyin_toneless("wangxiang_cn_dicts/base.small.dict.yaml", "egret_wubi_py_pinyin_base_small")
    gen_wubi_traditional()
