((magit-commit "--gpg-sign=F0DD604F43BD7D28BAB3AEEFDCCDED2EB72F6BAC")
 (magit-log:magit-log-mode "-n50" "--graph" "--color" "--decorate")
 (magit-patch-create)
 (magit-pull "--rebase" "--autostash")
 (magit-push "--force-with-lease"))
